// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package metric_stream

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.ExcludeFilters) != len(b.ko.Spec.ExcludeFilters) {
		delta.Add("Spec.ExcludeFilters", a.ko.Spec.ExcludeFilters, b.ko.Spec.ExcludeFilters)
	} else if len(a.ko.Spec.ExcludeFilters) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.ExcludeFilters, b.ko.Spec.ExcludeFilters) {
			delta.Add("Spec.ExcludeFilters", a.ko.Spec.ExcludeFilters, b.ko.Spec.ExcludeFilters)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.FirehoseARN, b.ko.Spec.FirehoseARN) {
		delta.Add("Spec.FirehoseARN", a.ko.Spec.FirehoseARN, b.ko.Spec.FirehoseARN)
	} else if a.ko.Spec.FirehoseARN != nil && b.ko.Spec.FirehoseARN != nil {
		if *a.ko.Spec.FirehoseARN != *b.ko.Spec.FirehoseARN {
			delta.Add("Spec.FirehoseARN", a.ko.Spec.FirehoseARN, b.ko.Spec.FirehoseARN)
		}
	}
	if len(a.ko.Spec.IncludeFilters) != len(b.ko.Spec.IncludeFilters) {
		delta.Add("Spec.IncludeFilters", a.ko.Spec.IncludeFilters, b.ko.Spec.IncludeFilters)
	} else if len(a.ko.Spec.IncludeFilters) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.IncludeFilters, b.ko.Spec.IncludeFilters) {
			delta.Add("Spec.IncludeFilters", a.ko.Spec.IncludeFilters, b.ko.Spec.IncludeFilters)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IncludeLinkedAccountsMetrics, b.ko.Spec.IncludeLinkedAccountsMetrics) {
		delta.Add("Spec.IncludeLinkedAccountsMetrics", a.ko.Spec.IncludeLinkedAccountsMetrics, b.ko.Spec.IncludeLinkedAccountsMetrics)
	} else if a.ko.Spec.IncludeLinkedAccountsMetrics != nil && b.ko.Spec.IncludeLinkedAccountsMetrics != nil {
		if *a.ko.Spec.IncludeLinkedAccountsMetrics != *b.ko.Spec.IncludeLinkedAccountsMetrics {
			delta.Add("Spec.IncludeLinkedAccountsMetrics", a.ko.Spec.IncludeLinkedAccountsMetrics, b.ko.Spec.IncludeLinkedAccountsMetrics)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.OutputFormat, b.ko.Spec.OutputFormat) {
		delta.Add("Spec.OutputFormat", a.ko.Spec.OutputFormat, b.ko.Spec.OutputFormat)
	} else if a.ko.Spec.OutputFormat != nil && b.ko.Spec.OutputFormat != nil {
		if *a.ko.Spec.OutputFormat != *b.ko.Spec.OutputFormat {
			delta.Add("Spec.OutputFormat", a.ko.Spec.OutputFormat, b.ko.Spec.OutputFormat)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleARN, b.ko.Spec.RoleARN) {
		delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
	} else if a.ko.Spec.RoleARN != nil && b.ko.Spec.RoleARN != nil {
		if *a.ko.Spec.RoleARN != *b.ko.Spec.RoleARN {
			delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
		}
	}
	if len(a.ko.Spec.StatisticsConfigurations) != len(b.ko.Spec.StatisticsConfigurations) {
		delta.Add("Spec.StatisticsConfigurations", a.ko.Spec.StatisticsConfigurations, b.ko.Spec.StatisticsConfigurations)
	} else if len(a.ko.Spec.StatisticsConfigurations) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.StatisticsConfigurations, b.ko.Spec.StatisticsConfigurations) {
			delta.Add("Spec.StatisticsConfigurations", a.ko.Spec.StatisticsConfigurations, b.ko.Spec.StatisticsConfigurations)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
