// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package metric_alarm

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cloudwatch-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.MetricAlarm{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	input.AlarmNames = []string{*r.ko.Spec.Name}

	var resp *svcsdk.DescribeAlarmsOutput
	resp, err = rm.sdkapi.DescribeAlarms(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeAlarms", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.MetricAlarms {
		if elem.ActionsEnabled != nil {
			ko.Spec.ActionsEnabled = elem.ActionsEnabled
		} else {
			ko.Spec.ActionsEnabled = nil
		}
		if elem.AlarmActions != nil {
			ko.Spec.AlarmActions = aws.StringSlice(elem.AlarmActions)
		} else {
			ko.Spec.AlarmActions = nil
		}
		if elem.AlarmArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.AlarmArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.AlarmDescription != nil {
			ko.Spec.AlarmDescription = elem.AlarmDescription
		} else {
			ko.Spec.AlarmDescription = nil
		}
		if elem.ComparisonOperator != "" {
			ko.Spec.ComparisonOperator = aws.String(string(elem.ComparisonOperator))
		} else {
			ko.Spec.ComparisonOperator = nil
		}
		if elem.DatapointsToAlarm != nil {
			datapointsToAlarmCopy := int64(*elem.DatapointsToAlarm)
			ko.Spec.DatapointsToAlarm = &datapointsToAlarmCopy
		} else {
			ko.Spec.DatapointsToAlarm = nil
		}
		if elem.Dimensions != nil {
			f8 := []*svcapitypes.Dimension{}
			for _, f8iter := range elem.Dimensions {
				f8elem := &svcapitypes.Dimension{}
				if f8iter.Name != nil {
					f8elem.Name = f8iter.Name
				}
				if f8iter.Value != nil {
					f8elem.Value = f8iter.Value
				}
				f8 = append(f8, f8elem)
			}
			ko.Spec.Dimensions = f8
		} else {
			ko.Spec.Dimensions = nil
		}
		if elem.EvaluateLowSampleCountPercentile != nil {
			ko.Spec.EvaluateLowSampleCountPercentile = elem.EvaluateLowSampleCountPercentile
		} else {
			ko.Spec.EvaluateLowSampleCountPercentile = nil
		}
		if elem.EvaluationCriteria != nil {
			f10 := &svcapitypes.EvaluationCriteria{}
			switch elem.EvaluationCriteria.(type) {
			case *svcsdktypes.EvaluationCriteriaMemberPromQLCriteria:
				f10f0 := elem.EvaluationCriteria.(*svcsdktypes.EvaluationCriteriaMemberPromQLCriteria)
				if f10f0 != nil {
					f10f0f0 := &svcapitypes.AlarmPromQLCriteria{}
					if f10f0.Value.PendingPeriod != nil {
						pendingPeriodCopy := int64(*f10f0.Value.PendingPeriod)
						f10f0f0.PendingPeriod = &pendingPeriodCopy
					}
					if f10f0.Value.Query != nil {
						f10f0f0.Query = f10f0.Value.Query
					}
					if f10f0.Value.RecoveryPeriod != nil {
						recoveryPeriodCopy := int64(*f10f0.Value.RecoveryPeriod)
						f10f0f0.RecoveryPeriod = &recoveryPeriodCopy
					}
					f10.PromQLCriteria = f10f0f0
				}
			}
			ko.Spec.EvaluationCriteria = f10
		} else {
			ko.Spec.EvaluationCriteria = nil
		}
		if elem.EvaluationInterval != nil {
			evaluationIntervalCopy := int64(*elem.EvaluationInterval)
			ko.Spec.EvaluationInterval = &evaluationIntervalCopy
		} else {
			ko.Spec.EvaluationInterval = nil
		}
		if elem.EvaluationPeriods != nil {
			evaluationPeriodsCopy := int64(*elem.EvaluationPeriods)
			ko.Spec.EvaluationPeriods = &evaluationPeriodsCopy
		} else {
			ko.Spec.EvaluationPeriods = nil
		}
		if elem.EvaluationWindow != nil {
			f14 := &svcapitypes.EvaluationWindow{}
			switch elem.EvaluationWindow.(type) {
			case *svcsdktypes.EvaluationWindowMemberSlidingWindow:
				f14f0 := elem.EvaluationWindow.(*svcsdktypes.EvaluationWindowMemberSlidingWindow)
				if f14f0 != nil {
					f14f0f0 := map[string]*string{}
					f14.SlidingWindow = f14f0f0
				}
			case *svcsdktypes.EvaluationWindowMemberWallClockWindow:
				f14f1 := elem.EvaluationWindow.(*svcsdktypes.EvaluationWindowMemberWallClockWindow)
				if f14f1 != nil {
					f14f1f1 := &svcapitypes.WallClockWindow{}
					if f14f1.Value.Timezone != nil {
						f14f1f1.Timezone = f14f1.Value.Timezone
					}
					f14.WallClockWindow = f14f1f1
				}
			}
			ko.Spec.EvaluationWindow = f14
		} else {
			ko.Spec.EvaluationWindow = nil
		}
		if elem.ExtendedStatistic != nil {
			ko.Spec.ExtendedStatistic = elem.ExtendedStatistic
		} else {
			ko.Spec.ExtendedStatistic = nil
		}
		if elem.InsufficientDataActions != nil {
			ko.Spec.InsufficientDataActions = aws.StringSlice(elem.InsufficientDataActions)
		} else {
			ko.Spec.InsufficientDataActions = nil
		}
		if elem.MetricName != nil {
			ko.Spec.MetricName = elem.MetricName
		} else {
			ko.Spec.MetricName = nil
		}
		if elem.Metrics != nil {
			f18 := []*svcapitypes.MetricDataQuery{}
			for _, f18iter := range elem.Metrics {
				f18elem := &svcapitypes.MetricDataQuery{}
				if f18iter.AccountId != nil {
					f18elem.AccountID = f18iter.AccountId
				}
				if f18iter.Expression != nil {
					f18elem.Expression = f18iter.Expression
				}
				if f18iter.Id != nil {
					f18elem.ID = f18iter.Id
				}
				if f18iter.Label != nil {
					f18elem.Label = f18iter.Label
				}
				if f18iter.MetricStat != nil {
					f18elemf4 := &svcapitypes.MetricStat{}
					if f18iter.MetricStat.Metric != nil {
						f18elemf4f0 := &svcapitypes.Metric{}
						if f18iter.MetricStat.Metric.Dimensions != nil {
							f18elemf4f0f0 := []*svcapitypes.Dimension{}
							for _, f18elemf4f0f0iter := range f18iter.MetricStat.Metric.Dimensions {
								f18elemf4f0f0elem := &svcapitypes.Dimension{}
								if f18elemf4f0f0iter.Name != nil {
									f18elemf4f0f0elem.Name = f18elemf4f0f0iter.Name
								}
								if f18elemf4f0f0iter.Value != nil {
									f18elemf4f0f0elem.Value = f18elemf4f0f0iter.Value
								}
								f18elemf4f0f0 = append(f18elemf4f0f0, f18elemf4f0f0elem)
							}
							f18elemf4f0.Dimensions = f18elemf4f0f0
						}
						if f18iter.MetricStat.Metric.MetricName != nil {
							f18elemf4f0.MetricName = f18iter.MetricStat.Metric.MetricName
						}
						if f18iter.MetricStat.Metric.Namespace != nil {
							f18elemf4f0.Namespace = f18iter.MetricStat.Metric.Namespace
						}
						f18elemf4.Metric = f18elemf4f0
					}
					if f18iter.MetricStat.Period != nil {
						periodCopy := int64(*f18iter.MetricStat.Period)
						f18elemf4.Period = &periodCopy
					}
					if f18iter.MetricStat.Stat != nil {
						f18elemf4.Stat = f18iter.MetricStat.Stat
					}
					if f18iter.MetricStat.Unit != "" {
						f18elemf4.Unit = aws.String(string(f18iter.MetricStat.Unit))
					}
					f18elem.MetricStat = f18elemf4
				}
				if f18iter.Period != nil {
					periodCopy := int64(*f18iter.Period)
					f18elem.Period = &periodCopy
				}
				if f18iter.ReturnData != nil {
					f18elem.ReturnData = f18iter.ReturnData
				}
				f18 = append(f18, f18elem)
			}
			ko.Spec.Metrics = f18
		} else {
			ko.Spec.Metrics = nil
		}
		if elem.Namespace != nil {
			ko.Spec.Namespace = elem.Namespace
		} else {
			ko.Spec.Namespace = nil
		}
		if elem.OKActions != nil {
			ko.Spec.OKActions = aws.StringSlice(elem.OKActions)
		} else {
			ko.Spec.OKActions = nil
		}
		if elem.Period != nil {
			periodCopy := int64(*elem.Period)
			ko.Spec.Period = &periodCopy
		} else {
			ko.Spec.Period = nil
		}
		if elem.Statistic != "" {
			ko.Spec.Statistic = aws.String(string(elem.Statistic))
		} else {
			ko.Spec.Statistic = nil
		}
		if elem.Threshold != nil {
			ko.Spec.Threshold = elem.Threshold
		} else {
			ko.Spec.Threshold = nil
		}
		if elem.ThresholdMetricId != nil {
			ko.Spec.ThresholdMetricID = elem.ThresholdMetricId
		} else {
			ko.Spec.ThresholdMetricID = nil
		}
		if elem.TreatMissingData != nil {
			ko.Spec.TreatMissingData = elem.TreatMissingData
		} else {
			ko.Spec.TreatMissingData = nil
		}
		if elem.Unit != "" {
			ko.Spec.Unit = aws.String(string(elem.Unit))
		} else {
			ko.Spec.Unit = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	// DescribeAlarms does not return tags — fetch them separately.
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		tagsInput := &svcsdk.ListTagsForResourceInput{
			ResourceARN: aws.String(string(*ko.Status.ACKResourceMetadata.ARN)),
		}
		tagsResp, tagsErr := rm.sdkapi.ListTagsForResource(ctx, tagsInput)
		rm.metrics.RecordAPICall("READ_MANY", "ListTagsForResource", tagsErr)
		if tagsErr != nil {
			return nil, tagsErr
		}
		ko.Spec.Tags = nil
		for _, t := range tagsResp.Tags {
			tCopy := svcapitypes.Tag{Key: t.Key, Value: t.Value}
			ko.Spec.Tags = append(ko.Spec.Tags, &tCopy)
		}
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return false
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeAlarmsInput, error) {
	res := &svcsdk.DescribeAlarmsInput{}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutMetricAlarmOutput
	_ = resp
	resp, err = rm.sdkapi.PutMetricAlarm(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "PutMetricAlarm", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.PutMetricAlarmInput, error) {
	res := &svcsdk.PutMetricAlarmInput{}

	if r.ko.Spec.ActionsEnabled != nil {
		res.ActionsEnabled = r.ko.Spec.ActionsEnabled
	}
	if r.ko.Spec.AlarmActions != nil {
		res.AlarmActions = aws.ToStringSlice(r.ko.Spec.AlarmActions)
	}
	if r.ko.Spec.AlarmDescription != nil {
		res.AlarmDescription = r.ko.Spec.AlarmDescription
	}
	if r.ko.Spec.Name != nil {
		res.AlarmName = r.ko.Spec.Name
	}
	if r.ko.Spec.ComparisonOperator != nil {
		res.ComparisonOperator = svcsdktypes.ComparisonOperator(*r.ko.Spec.ComparisonOperator)
	}
	if r.ko.Spec.DatapointsToAlarm != nil {
		datapointsToAlarmCopy0 := *r.ko.Spec.DatapointsToAlarm
		if datapointsToAlarmCopy0 > math.MaxInt32 || datapointsToAlarmCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DatapointsToAlarm is of type int32")
		}
		datapointsToAlarmCopy := int32(datapointsToAlarmCopy0)
		res.DatapointsToAlarm = &datapointsToAlarmCopy
	}
	if r.ko.Spec.Dimensions != nil {
		f6 := []svcsdktypes.Dimension{}
		for _, f6iter := range r.ko.Spec.Dimensions {
			f6elem := &svcsdktypes.Dimension{}
			if f6iter.Name != nil {
				f6elem.Name = f6iter.Name
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, *f6elem)
		}
		res.Dimensions = f6
	}
	if r.ko.Spec.EvaluateLowSampleCountPercentile != nil {
		res.EvaluateLowSampleCountPercentile = r.ko.Spec.EvaluateLowSampleCountPercentile
	}
	if r.ko.Spec.EvaluationCriteria != nil {
		var f8 svcsdktypes.EvaluationCriteria
		isInterfaceSet := false
		if r.ko.Spec.EvaluationCriteria.PromQLCriteria != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for PromQLCriteria"))
			}
			f8f0Parent := &svcsdktypes.EvaluationCriteriaMemberPromQLCriteria{}
			f8f0 := &svcsdktypes.AlarmPromQLCriteria{}
			if r.ko.Spec.EvaluationCriteria.PromQLCriteria.PendingPeriod != nil {
				pendingPeriodCopy0 := *r.ko.Spec.EvaluationCriteria.PromQLCriteria.PendingPeriod
				if pendingPeriodCopy0 > math.MaxInt32 || pendingPeriodCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field PendingPeriod is of type int32")
				}
				pendingPeriodCopy := int32(pendingPeriodCopy0)
				f8f0.PendingPeriod = &pendingPeriodCopy
			}
			if r.ko.Spec.EvaluationCriteria.PromQLCriteria.Query != nil {
				f8f0.Query = r.ko.Spec.EvaluationCriteria.PromQLCriteria.Query
			}
			if r.ko.Spec.EvaluationCriteria.PromQLCriteria.RecoveryPeriod != nil {
				recoveryPeriodCopy0 := *r.ko.Spec.EvaluationCriteria.PromQLCriteria.RecoveryPeriod
				if recoveryPeriodCopy0 > math.MaxInt32 || recoveryPeriodCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field RecoveryPeriod is of type int32")
				}
				recoveryPeriodCopy := int32(recoveryPeriodCopy0)
				f8f0.RecoveryPeriod = &recoveryPeriodCopy
			}
			f8f0Parent.Value = *f8f0
			f8 = f8f0Parent
			isInterfaceSet = true
		}
		res.EvaluationCriteria = f8
	}
	if r.ko.Spec.EvaluationInterval != nil {
		evaluationIntervalCopy0 := *r.ko.Spec.EvaluationInterval
		if evaluationIntervalCopy0 > math.MaxInt32 || evaluationIntervalCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field EvaluationInterval is of type int32")
		}
		evaluationIntervalCopy := int32(evaluationIntervalCopy0)
		res.EvaluationInterval = &evaluationIntervalCopy
	}
	if r.ko.Spec.EvaluationPeriods != nil {
		evaluationPeriodsCopy0 := *r.ko.Spec.EvaluationPeriods
		if evaluationPeriodsCopy0 > math.MaxInt32 || evaluationPeriodsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field EvaluationPeriods is of type int32")
		}
		evaluationPeriodsCopy := int32(evaluationPeriodsCopy0)
		res.EvaluationPeriods = &evaluationPeriodsCopy
	}
	if r.ko.Spec.EvaluationWindow != nil {
		var f11 svcsdktypes.EvaluationWindow
		isInterfaceSet := false
		if r.ko.Spec.EvaluationWindow.SlidingWindow != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SlidingWindow"))
			}
			f11f0Parent := &svcsdktypes.EvaluationWindowMemberSlidingWindow{}
			f11f0 := &svcsdktypes.SlidingWindow{}
			f11f0Parent.Value = *f11f0
			f11 = f11f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.EvaluationWindow.WallClockWindow != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for WallClockWindow"))
			}
			f11f1Parent := &svcsdktypes.EvaluationWindowMemberWallClockWindow{}
			f11f1 := &svcsdktypes.WallClockWindow{}
			if r.ko.Spec.EvaluationWindow.WallClockWindow.Timezone != nil {
				f11f1.Timezone = r.ko.Spec.EvaluationWindow.WallClockWindow.Timezone
			}
			f11f1Parent.Value = *f11f1
			f11 = f11f1Parent
			isInterfaceSet = true
		}
		res.EvaluationWindow = f11
	}
	if r.ko.Spec.ExtendedStatistic != nil {
		res.ExtendedStatistic = r.ko.Spec.ExtendedStatistic
	}
	if r.ko.Spec.InsufficientDataActions != nil {
		res.InsufficientDataActions = aws.ToStringSlice(r.ko.Spec.InsufficientDataActions)
	}
	if r.ko.Spec.MetricName != nil {
		res.MetricName = r.ko.Spec.MetricName
	}
	if r.ko.Spec.Metrics != nil {
		f15 := []svcsdktypes.MetricDataQuery{}
		for _, f15iter := range r.ko.Spec.Metrics {
			f15elem := &svcsdktypes.MetricDataQuery{}
			if f15iter.AccountID != nil {
				f15elem.AccountId = f15iter.AccountID
			}
			if f15iter.Expression != nil {
				f15elem.Expression = f15iter.Expression
			}
			if f15iter.ID != nil {
				f15elem.Id = f15iter.ID
			}
			if f15iter.Label != nil {
				f15elem.Label = f15iter.Label
			}
			if f15iter.MetricStat != nil {
				f15elemf4 := &svcsdktypes.MetricStat{}
				if f15iter.MetricStat.Metric != nil {
					f15elemf4f0 := &svcsdktypes.Metric{}
					if f15iter.MetricStat.Metric.Dimensions != nil {
						f15elemf4f0f0 := []svcsdktypes.Dimension{}
						for _, f15elemf4f0f0iter := range f15iter.MetricStat.Metric.Dimensions {
							f15elemf4f0f0elem := &svcsdktypes.Dimension{}
							if f15elemf4f0f0iter.Name != nil {
								f15elemf4f0f0elem.Name = f15elemf4f0f0iter.Name
							}
							if f15elemf4f0f0iter.Value != nil {
								f15elemf4f0f0elem.Value = f15elemf4f0f0iter.Value
							}
							f15elemf4f0f0 = append(f15elemf4f0f0, *f15elemf4f0f0elem)
						}
						f15elemf4f0.Dimensions = f15elemf4f0f0
					}
					if f15iter.MetricStat.Metric.MetricName != nil {
						f15elemf4f0.MetricName = f15iter.MetricStat.Metric.MetricName
					}
					if f15iter.MetricStat.Metric.Namespace != nil {
						f15elemf4f0.Namespace = f15iter.MetricStat.Metric.Namespace
					}
					f15elemf4.Metric = f15elemf4f0
				}
				if f15iter.MetricStat.Period != nil {
					periodCopy0 := *f15iter.MetricStat.Period
					if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Period is of type int32")
					}
					periodCopy := int32(periodCopy0)
					f15elemf4.Period = &periodCopy
				}
				if f15iter.MetricStat.Stat != nil {
					f15elemf4.Stat = f15iter.MetricStat.Stat
				}
				if f15iter.MetricStat.Unit != nil {
					f15elemf4.Unit = svcsdktypes.StandardUnit(*f15iter.MetricStat.Unit)
				}
				f15elem.MetricStat = f15elemf4
			}
			if f15iter.Period != nil {
				periodCopy0 := *f15iter.Period
				if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field Period is of type int32")
				}
				periodCopy := int32(periodCopy0)
				f15elem.Period = &periodCopy
			}
			if f15iter.ReturnData != nil {
				f15elem.ReturnData = f15iter.ReturnData
			}
			f15 = append(f15, *f15elem)
		}
		res.Metrics = f15
	}
	if r.ko.Spec.Namespace != nil {
		res.Namespace = r.ko.Spec.Namespace
	}
	if r.ko.Spec.OKActions != nil {
		res.OKActions = aws.ToStringSlice(r.ko.Spec.OKActions)
	}
	if r.ko.Spec.Period != nil {
		periodCopy0 := *r.ko.Spec.Period
		if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Period is of type int32")
		}
		periodCopy := int32(periodCopy0)
		res.Period = &periodCopy
	}
	if r.ko.Spec.Statistic != nil {
		res.Statistic = svcsdktypes.Statistic(*r.ko.Spec.Statistic)
	}
	if r.ko.Spec.Tags != nil {
		f20 := []svcsdktypes.Tag{}
		for _, f20iter := range r.ko.Spec.Tags {
			f20elem := &svcsdktypes.Tag{}
			if f20iter.Key != nil {
				f20elem.Key = f20iter.Key
			}
			if f20iter.Value != nil {
				f20elem.Value = f20iter.Value
			}
			f20 = append(f20, *f20elem)
		}
		res.Tags = f20
	}
	if r.ko.Spec.Threshold != nil {
		res.Threshold = r.ko.Spec.Threshold
	}
	if r.ko.Spec.ThresholdMetricID != nil {
		res.ThresholdMetricId = r.ko.Spec.ThresholdMetricID
	}
	if r.ko.Spec.TreatMissingData != nil {
		res.TreatMissingData = r.ko.Spec.TreatMissingData
	}
	if r.ko.Spec.Unit != nil {
		res.Unit = svcsdktypes.StandardUnit(*r.ko.Spec.Unit)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutMetricAlarmOutput
	_ = resp
	resp, err = rm.sdkapi.PutMetricAlarm(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutMetricAlarm", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.PutMetricAlarmInput, error) {
	res := &svcsdk.PutMetricAlarmInput{}

	if r.ko.Spec.ActionsEnabled != nil {
		res.ActionsEnabled = r.ko.Spec.ActionsEnabled
	}
	if r.ko.Spec.AlarmActions != nil {
		res.AlarmActions = aws.ToStringSlice(r.ko.Spec.AlarmActions)
	}
	if r.ko.Spec.AlarmDescription != nil {
		res.AlarmDescription = r.ko.Spec.AlarmDescription
	}
	if r.ko.Spec.Name != nil {
		res.AlarmName = r.ko.Spec.Name
	}
	if r.ko.Spec.ComparisonOperator != nil {
		res.ComparisonOperator = svcsdktypes.ComparisonOperator(*r.ko.Spec.ComparisonOperator)
	}
	if r.ko.Spec.DatapointsToAlarm != nil {
		datapointsToAlarmCopy0 := *r.ko.Spec.DatapointsToAlarm
		if datapointsToAlarmCopy0 > math.MaxInt32 || datapointsToAlarmCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DatapointsToAlarm is of type int32")
		}
		datapointsToAlarmCopy := int32(datapointsToAlarmCopy0)
		res.DatapointsToAlarm = &datapointsToAlarmCopy
	}
	if r.ko.Spec.Dimensions != nil {
		f6 := []svcsdktypes.Dimension{}
		for _, f6iter := range r.ko.Spec.Dimensions {
			f6elem := &svcsdktypes.Dimension{}
			if f6iter.Name != nil {
				f6elem.Name = f6iter.Name
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, *f6elem)
		}
		res.Dimensions = f6
	}
	if r.ko.Spec.EvaluateLowSampleCountPercentile != nil {
		res.EvaluateLowSampleCountPercentile = r.ko.Spec.EvaluateLowSampleCountPercentile
	}
	if r.ko.Spec.EvaluationCriteria != nil {
		var f8 svcsdktypes.EvaluationCriteria
		isInterfaceSet := false
		if r.ko.Spec.EvaluationCriteria.PromQLCriteria != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for PromQLCriteria"))
			}
			f8f0Parent := &svcsdktypes.EvaluationCriteriaMemberPromQLCriteria{}
			f8f0 := &svcsdktypes.AlarmPromQLCriteria{}
			if r.ko.Spec.EvaluationCriteria.PromQLCriteria.PendingPeriod != nil {
				pendingPeriodCopy0 := *r.ko.Spec.EvaluationCriteria.PromQLCriteria.PendingPeriod
				if pendingPeriodCopy0 > math.MaxInt32 || pendingPeriodCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field PendingPeriod is of type int32")
				}
				pendingPeriodCopy := int32(pendingPeriodCopy0)
				f8f0.PendingPeriod = &pendingPeriodCopy
			}
			if r.ko.Spec.EvaluationCriteria.PromQLCriteria.Query != nil {
				f8f0.Query = r.ko.Spec.EvaluationCriteria.PromQLCriteria.Query
			}
			if r.ko.Spec.EvaluationCriteria.PromQLCriteria.RecoveryPeriod != nil {
				recoveryPeriodCopy0 := *r.ko.Spec.EvaluationCriteria.PromQLCriteria.RecoveryPeriod
				if recoveryPeriodCopy0 > math.MaxInt32 || recoveryPeriodCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field RecoveryPeriod is of type int32")
				}
				recoveryPeriodCopy := int32(recoveryPeriodCopy0)
				f8f0.RecoveryPeriod = &recoveryPeriodCopy
			}
			f8f0Parent.Value = *f8f0
			f8 = f8f0Parent
			isInterfaceSet = true
		}
		res.EvaluationCriteria = f8
	}
	if r.ko.Spec.EvaluationInterval != nil {
		evaluationIntervalCopy0 := *r.ko.Spec.EvaluationInterval
		if evaluationIntervalCopy0 > math.MaxInt32 || evaluationIntervalCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field EvaluationInterval is of type int32")
		}
		evaluationIntervalCopy := int32(evaluationIntervalCopy0)
		res.EvaluationInterval = &evaluationIntervalCopy
	}
	if r.ko.Spec.EvaluationPeriods != nil {
		evaluationPeriodsCopy0 := *r.ko.Spec.EvaluationPeriods
		if evaluationPeriodsCopy0 > math.MaxInt32 || evaluationPeriodsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field EvaluationPeriods is of type int32")
		}
		evaluationPeriodsCopy := int32(evaluationPeriodsCopy0)
		res.EvaluationPeriods = &evaluationPeriodsCopy
	}
	if r.ko.Spec.EvaluationWindow != nil {
		var f11 svcsdktypes.EvaluationWindow
		isInterfaceSet := false
		if r.ko.Spec.EvaluationWindow.SlidingWindow != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SlidingWindow"))
			}
			f11f0Parent := &svcsdktypes.EvaluationWindowMemberSlidingWindow{}
			f11f0 := &svcsdktypes.SlidingWindow{}
			f11f0Parent.Value = *f11f0
			f11 = f11f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.EvaluationWindow.WallClockWindow != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for WallClockWindow"))
			}
			f11f1Parent := &svcsdktypes.EvaluationWindowMemberWallClockWindow{}
			f11f1 := &svcsdktypes.WallClockWindow{}
			if r.ko.Spec.EvaluationWindow.WallClockWindow.Timezone != nil {
				f11f1.Timezone = r.ko.Spec.EvaluationWindow.WallClockWindow.Timezone
			}
			f11f1Parent.Value = *f11f1
			f11 = f11f1Parent
			isInterfaceSet = true
		}
		res.EvaluationWindow = f11
	}
	if r.ko.Spec.ExtendedStatistic != nil {
		res.ExtendedStatistic = r.ko.Spec.ExtendedStatistic
	}
	if r.ko.Spec.InsufficientDataActions != nil {
		res.InsufficientDataActions = aws.ToStringSlice(r.ko.Spec.InsufficientDataActions)
	}
	if r.ko.Spec.MetricName != nil {
		res.MetricName = r.ko.Spec.MetricName
	}
	if r.ko.Spec.Metrics != nil {
		f15 := []svcsdktypes.MetricDataQuery{}
		for _, f15iter := range r.ko.Spec.Metrics {
			f15elem := &svcsdktypes.MetricDataQuery{}
			if f15iter.AccountID != nil {
				f15elem.AccountId = f15iter.AccountID
			}
			if f15iter.Expression != nil {
				f15elem.Expression = f15iter.Expression
			}
			if f15iter.ID != nil {
				f15elem.Id = f15iter.ID
			}
			if f15iter.Label != nil {
				f15elem.Label = f15iter.Label
			}
			if f15iter.MetricStat != nil {
				f15elemf4 := &svcsdktypes.MetricStat{}
				if f15iter.MetricStat.Metric != nil {
					f15elemf4f0 := &svcsdktypes.Metric{}
					if f15iter.MetricStat.Metric.Dimensions != nil {
						f15elemf4f0f0 := []svcsdktypes.Dimension{}
						for _, f15elemf4f0f0iter := range f15iter.MetricStat.Metric.Dimensions {
							f15elemf4f0f0elem := &svcsdktypes.Dimension{}
							if f15elemf4f0f0iter.Name != nil {
								f15elemf4f0f0elem.Name = f15elemf4f0f0iter.Name
							}
							if f15elemf4f0f0iter.Value != nil {
								f15elemf4f0f0elem.Value = f15elemf4f0f0iter.Value
							}
							f15elemf4f0f0 = append(f15elemf4f0f0, *f15elemf4f0f0elem)
						}
						f15elemf4f0.Dimensions = f15elemf4f0f0
					}
					if f15iter.MetricStat.Metric.MetricName != nil {
						f15elemf4f0.MetricName = f15iter.MetricStat.Metric.MetricName
					}
					if f15iter.MetricStat.Metric.Namespace != nil {
						f15elemf4f0.Namespace = f15iter.MetricStat.Metric.Namespace
					}
					f15elemf4.Metric = f15elemf4f0
				}
				if f15iter.MetricStat.Period != nil {
					periodCopy0 := *f15iter.MetricStat.Period
					if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Period is of type int32")
					}
					periodCopy := int32(periodCopy0)
					f15elemf4.Period = &periodCopy
				}
				if f15iter.MetricStat.Stat != nil {
					f15elemf4.Stat = f15iter.MetricStat.Stat
				}
				if f15iter.MetricStat.Unit != nil {
					f15elemf4.Unit = svcsdktypes.StandardUnit(*f15iter.MetricStat.Unit)
				}
				f15elem.MetricStat = f15elemf4
			}
			if f15iter.Period != nil {
				periodCopy0 := *f15iter.Period
				if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field Period is of type int32")
				}
				periodCopy := int32(periodCopy0)
				f15elem.Period = &periodCopy
			}
			if f15iter.ReturnData != nil {
				f15elem.ReturnData = f15iter.ReturnData
			}
			f15 = append(f15, *f15elem)
		}
		res.Metrics = f15
	}
	if r.ko.Spec.Namespace != nil {
		res.Namespace = r.ko.Spec.Namespace
	}
	if r.ko.Spec.OKActions != nil {
		res.OKActions = aws.ToStringSlice(r.ko.Spec.OKActions)
	}
	if r.ko.Spec.Period != nil {
		periodCopy0 := *r.ko.Spec.Period
		if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Period is of type int32")
		}
		periodCopy := int32(periodCopy0)
		res.Period = &periodCopy
	}
	if r.ko.Spec.Statistic != nil {
		res.Statistic = svcsdktypes.Statistic(*r.ko.Spec.Statistic)
	}
	if r.ko.Spec.Tags != nil {
		f20 := []svcsdktypes.Tag{}
		for _, f20iter := range r.ko.Spec.Tags {
			f20elem := &svcsdktypes.Tag{}
			if f20iter.Key != nil {
				f20elem.Key = f20iter.Key
			}
			if f20iter.Value != nil {
				f20elem.Value = f20iter.Value
			}
			f20 = append(f20, *f20elem)
		}
		res.Tags = f20
	}
	if r.ko.Spec.Threshold != nil {
		res.Threshold = r.ko.Spec.Threshold
	}
	if r.ko.Spec.ThresholdMetricID != nil {
		res.ThresholdMetricId = r.ko.Spec.ThresholdMetricID
	}
	if r.ko.Spec.TreatMissingData != nil {
		res.TreatMissingData = r.ko.Spec.TreatMissingData
	}
	if r.ko.Spec.Unit != nil {
		res.Unit = svcsdktypes.StandardUnit(*r.ko.Spec.Unit)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	input.AlarmNames = []string{*r.ko.Spec.Name}

	var resp *svcsdk.DeleteAlarmsOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAlarms(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAlarms", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAlarmsInput, error) {
	res := &svcsdk.DeleteAlarmsInput{}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.MetricAlarm,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
